# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(637, 519)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 641, 521))
        self.label.setStyleSheet("opacity:0.4;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pngwing.com.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_saudacao = QtWidgets.QLabel(Form)
        self.label_saudacao.setGeometry(QtCore.QRect(30, 160, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(26)
        self.label_saudacao.setFont(font)
        self.label_saudacao.setStyleSheet("color:rgb(85, 0, 0)")
        self.label_saudacao.setText("")
        self.label_saudacao.setObjectName("label_saudacao")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
