# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 260)
        self.lineEdit_login = QtWidgets.QLineEdit(Form)
        self.lineEdit_login.setGeometry(QtCore.QRect(70, 70, 281, 22))
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_senha = QtWidgets.QLineEdit(Form)
        self.lineEdit_senha.setGeometry(QtCore.QRect(70, 110, 281, 22))
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.pushButton_entrar = QtWidgets.QPushButton(Form)
        self.pushButton_entrar.setGeometry(QtCore.QRect(160, 150, 93, 28))
        self.pushButton_entrar.setObjectName("pushButton_entrar")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_cadastro = QtWidgets.QPushButton(Form)
        self.pushButton_cadastro.setGeometry(QtCore.QRect(160, 190, 93, 28))
        self.pushButton_cadastro.setObjectName("pushButton_cadastro")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_login.setPlaceholderText(_translate("Form", "Digite Seu Login"))
        self.lineEdit_senha.setPlaceholderText(_translate("Form", "Digite sua senha"))
        self.pushButton_entrar.setText(_translate("Form", "Entrar"))
        self.label.setText(_translate("Form", "Login"))
        self.pushButton_cadastro.setText(_translate("Form", "Cadastro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
