# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 248)
        self.lineEdit_senha = QtWidgets.QLineEdit(Form)
        self.lineEdit_senha.setGeometry(QtCore.QRect(60, 110, 281, 22))
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.lineEdit_nome = QtWidgets.QLineEdit(Form)
        self.lineEdit_nome.setGeometry(QtCore.QRect(60, 70, 281, 22))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(60, 150, 281, 22))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_cadastrar = QtWidgets.QPushButton(Form)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(150, 200, 93, 28))
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_senha.setPlaceholderText(_translate("Form", "Digite sua senha"))
        self.lineEdit_nome.setPlaceholderText(_translate("Form", "Digite seu nome"))
        self.lineEdit_email.setPlaceholderText(_translate("Form", "Digite seu E-mail"))
        self.pushButton_cadastrar.setText(_translate("Form", "Entrar"))
        self.label.setText(_translate("Form", "Cadastro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
