# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(887, 662)
        Form.setStyleSheet("")
        self.pushButton_cadastrar = QtWidgets.QPushButton(Form)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(230, 380, 93, 28))
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 200, 79, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(85, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 521, 651))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pngwing.com.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(120, 330, 321, 22))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_nome = QtWidgets.QLineEdit(Form)
        self.lineEdit_nome.setGeometry(QtCore.QRect(120, 250, 321, 22))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_senha = QtWidgets.QLineEdit(Form)
        self.lineEdit_senha.setGeometry(QtCore.QRect(120, 290, 321, 22))
        self.lineEdit_senha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_senha.setInputMask("")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setDragEnabled(False)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.label_2.raise_()
        self.lineEdit_nome.raise_()
        self.lineEdit_senha.raise_()
        self.pushButton_cadastrar.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_cadastrar.setText(_translate("Form", "Cadastrar"))
        self.label.setText(_translate("Form", "Cadastro"))
        self.lineEdit_email.setPlaceholderText(_translate("Form", "Digite seu E-mail"))
        self.lineEdit_nome.setPlaceholderText(_translate("Form", "Digite seu nome"))
        self.lineEdit_senha.setPlaceholderText(_translate("Form", "Digite sua senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
