# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex15.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(315, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 258, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_qtd = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_qtd.setObjectName("lineEdit_qtd")
        self.verticalLayout.addWidget(self.lineEdit_qtd)
        self.lineEditPreco = QtWidgets.QLineEdit(self.widget)
        self.lineEditPreco.setObjectName("lineEditPreco")
        self.verticalLayout.addWidget(self.lineEditPreco)
        self.listWidgetPrecos = QtWidgets.QListWidget(self.widget)
        self.listWidgetPrecos.setObjectName("listWidgetPrecos")
        self.verticalLayout.addWidget(self.listWidgetPrecos)
        self.labelMedia = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMedia.setFont(font)
        self.labelMedia.setText("")
        self.labelMedia.setObjectName("labelMedia")
        self.verticalLayout.addWidget(self.labelMedia)
        self.btnCalcularMedia = QtWidgets.QPushButton(self.widget)
        self.btnCalcularMedia.setObjectName("btnCalcularMedia")
        self.verticalLayout.addWidget(self.btnCalcularMedia)
        self.btnAdicionar = QtWidgets.QPushButton(self.widget)
        self.btnAdicionar.setObjectName("btnAdicionar")
        self.verticalLayout.addWidget(self.btnAdicionar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 315, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_qtd.setPlaceholderText(_translate("MainWindow", "Quantidade de CDs comprados"))
        self.lineEditPreco.setPlaceholderText(_translate("MainWindow", "Preço do CD"))
        self.btnCalcularMedia.setText(_translate("MainWindow", "Media"))
        self.btnAdicionar.setText(_translate("MainWindow", "Adicionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
