# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 531)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color:qradialgradient(spread:reflect, cx:0.886364, cy:0.176, radius:1.584, fx:0.938, fy:0, stop:0.482955 rgba(0, 61, 102, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 290, 481, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(481, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(481, 16777215))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidget.setStyleSheet("QHeaderView::section{\n"
"    background-color:rgba(0,0,0,0.5);\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgba(0,0,0,.5);\n"
"    border-radius:10px;\n"
"    gridline-color: rgba(0,0,0,.5);\n"
"    text-align:center;\n"
"}\n"
"QTableWidget::item {\n"
"            padding: 5px; \n"
"        color: white;\n"
"        width:100px;               /* Espaçamento interno */\n"
"        text-align:center;\n"
"        }\n"
"\n"
"QTableWidget::item:selected {\n"
"            background-color: none;  /* Cor de fundo ao selecionar */\n"
"            color: white;    \n"
"width:100px;\n"
"text-align:center;           /* Cor do texto ao selecionar */\n"
"        }\n"
"        QTableWidget::item:nth-child(odd) {\n"
"           background-color: none;\n"
"width:100px;\n"
"color: white; \n"
"text-align:center;  /* Cor de fundo para linhas ímpares */\n"
"        }\n"
"        QTableWidget::item:nth-child(even) {\n"
"            background-color: none;\n"
"width:100px;\n"
"    color: white;\n"
"text-align:center;/* Cor de fundo para linhas pares */\n"
"        }")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.pushButton_player = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_player.setGeometry(QtCore.QRect(150, 260, 75, 23))
        self.pushButton_player.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_player.setStyleSheet("QPushButton {\n"
"    background-color: rgb(24, 24, 24); /* Default background color */\n"
"    color: white;              /* Default text color */\n"
"    border: none;             /* Remove border */         \n"
"    border-radius: 5px;      /* Rounded corners */\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    width:100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Background color on hover */\n"
"\n"
"}")
        self.pushButton_player.setObjectName("pushButton_player")
        self.pushButton_pause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(240, 260, 75, 23))
        self.pushButton_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pause.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(24, 24, 24); /* Default background color */\n"
"    color: white;              /* Default text color */\n"
"    border: none;             /* Remove border */         \n"
"    border-radius: 5px;      /* Rounded corners */\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Background color on hover */\n"
"}")
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(280, 20, 180, 180))
        self.label_imagem.setStyleSheet("QLabel{\n"
"    border-radius: 100px;\n"
"    background-color:none;\n"
"}")
        self.label_imagem.setText("")
        self.label_imagem.setObjectName("label_imagem")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(10, 10, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(16)
        self.label_nome.setFont(font)
        self.label_nome.setStyleSheet("color:white;\n"
"background-color:none;")
        self.label_nome.setText("")
        self.label_nome.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nome.setWordWrap(True)
        self.label_nome.setObjectName("label_nome")
        self.label_art = QtWidgets.QLabel(self.centralwidget)
        self.label_art.setGeometry(QtCore.QRect(10, 100, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_art.setFont(font)
        self.label_art.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:none;\n"
"")
        self.label_art.setText("")
        self.label_art.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_art.setWordWrap(True)
        self.label_art.setObjectName("label_art")
        self.label_duracao = QtWidgets.QLabel(self.centralwidget)
        self.label_duracao.setGeometry(QtCore.QRect(190, 140, 71, 21))
        self.label_duracao.setStyleSheet("background-color:none;\n"
"color:white;")
        self.label_duracao.setText("")
        self.label_duracao.setObjectName("label_duracao")
        self.sliderProgress = QtWidgets.QSlider(self.centralwidget)
        self.sliderProgress.setGeometry(QtCore.QRect(40, 230, 401, 22))
        self.sliderProgress.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: #eee;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255, 85, 0);\n"
"    border: 1px solid #ff2200;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -3px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #ff2200;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #ff5733;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #ddd;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.sliderProgress.setMaximum(100)
        self.sliderProgress.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProgress.setObjectName("sliderProgress")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "a"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        self.pushButton_player.setText(_translate("MainWindow", "Play"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
