# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_cadastro = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastro.setGeometry(QtCore.QRect(50, 40, 171, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_cadastro.setFont(font)
        self.pushButton_cadastro.setObjectName("pushButton_cadastro")
        self.pushButton_comprar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_comprar.setGeometry(QtCore.QRect(230, 40, 171, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_comprar.setFont(font)
        self.pushButton_comprar.setObjectName("pushButton_comprar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_cadastro.setText(_translate("MainWindow", "Cadastrar Produto"))
        self.pushButton_comprar.setText(_translate("MainWindow", "Comprar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
