# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex21.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_item = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_item.setGeometry(QtCore.QRect(20, 20, 161, 20))
        self.lineEdit_item.setObjectName("lineEdit_item")
        self.lineEdit_preco = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_preco.setGeometry(QtCore.QRect(20, 50, 161, 20))
        self.lineEdit_preco.setObjectName("lineEdit_preco")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabelaProdutos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelaProdutos.setGeometry(QtCore.QRect(20, 80, 256, 192))
        self.tabelaProdutos.setLineWidth(1)
        self.tabelaProdutos.setMidLineWidth(-1)
        self.tabelaProdutos.setColumnCount(2)
        self.tabelaProdutos.setObjectName("tabelaProdutos")
        self.tabelaProdutos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaProdutos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaProdutos.setHorizontalHeaderItem(1, item)
        self.label_carrinho = QtWidgets.QLabel(self.centralwidget)
        self.label_carrinho.setGeometry(QtCore.QRect(370, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_carrinho.setFont(font)
        self.label_carrinho.setAlignment(QtCore.Qt.AlignCenter)
        self.label_carrinho.setObjectName("label_carrinho")
        self.pushButton_selecionarItem = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selecionarItem.setGeometry(QtCore.QRect(100, 290, 91, 23))
        self.pushButton_selecionarItem.setObjectName("pushButton_selecionarItem")
        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(390, 320, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_total.setFont(font)
        self.label_total.setText("")
        self.label_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total.setObjectName("label_total")
        self.pushButton_comprar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_comprar.setGeometry(QtCore.QRect(460, 290, 75, 23))
        self.pushButton_comprar.setObjectName("pushButton_comprar")
        self.tabelaCarrinho = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelaCarrinho.setGeometry(QtCore.QRect(330, 80, 311, 192))
        self.tabelaCarrinho.setLineWidth(1)
        self.tabelaCarrinho.setMidLineWidth(-1)
        self.tabelaCarrinho.setColumnCount(3)
        self.tabelaCarrinho.setObjectName("tabelaCarrinho")
        self.tabelaCarrinho.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaCarrinho.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaCarrinho.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaCarrinho.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 655, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_item.setPlaceholderText(_translate("MainWindow", "Adicionar Item"))
        self.lineEdit_preco.setPlaceholderText(_translate("MainWindow", "Valor do Item"))
        self.pushButton.setText(_translate("MainWindow", "Adicionar"))
        item = self.tabelaProdutos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Produto"))
        item = self.tabelaProdutos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Preço"))
        self.label_carrinho.setText(_translate("MainWindow", "Carrinho"))
        self.pushButton_selecionarItem.setText(_translate("MainWindow", "Selecionar Item"))
        self.pushButton_comprar.setText(_translate("MainWindow", "Comprar"))
        item = self.tabelaCarrinho.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Produto"))
        item = self.tabelaCarrinho.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Preço"))
        item = self.tabelaCarrinho.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantidade"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
